services:
    php-app:
        build:
            context: .
        container_name: laravel-app
        ports:
          - "9000:9000"
          - "5173:5173"
        volumes:
          - .:/var/www
          - laravel_logs:/var/www/html/storage/logs
        environment:
          - DB_HOST=mysql            # Set environment variables for database connection
          - DB_PORT=3306
          - DB_DATABASE=laravel # Replace 'laravel' with your actual database name
          - DB_USERNAME=laravel # Replace 'laravel' with your database username
          - DB_PASSWORD=laravel # Replace 'laravel' with your database password
          - XDEBUG_CONFIG=client_port=9003

        depends_on:
            - mysql
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
            - laravel_logs:/var/www/html/storage/logs
        ports:
            - "8000:80"
        depends_on:
            - php-app
        networks:
            - laravel

    mysql:
        image: mysql
        container_name: mysql
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=laravel # Replace 'laravel' with your root password
            - MYSQL_DATABASE=laravel # Replace 'laravel' with your database name
            - MYSQL_USER=laravel # Replace 'laravel' with your database username
            - MYSQL_PASSWORD=laravel # Replace 'laravel' with your database password
        ports:
            - '3306:3306'
        networks:
            - laravel

volumes:
    mysql_data:
    laravel_logs:

networks:
    laravel:
        driver: bridge


